### ISSUE TITLE
Migrate LamaEvents to the new servers 

### ISSUE THREAD

**Issue by ErkanBasar** [LanguageMachines/LamaEvents#11]
## Summary
[Ponyland](https://ponyland.science.ru.nl/wiki:ponyland:about) servers are renewed, and thus, all of the applications running are being migrated to the new machines. The assignees of this issue should arrange a meeting together to perform the migration.

## Steps
- [x] Move the LamaEvents MongoDB database to the new servers
- [x] Move the LamaEvents application to the new servers

**Comment by Woseseltops** [comment]
![image](https://user-images.githubusercontent.com/1909317/43709150-638ba88c-996c-11e8-9881-12dae4f3c6dc.png)
