### ISSUE TITLE
Put the website online again

### ISSUE THREAD

**Issue by ErkanBasar** [LanguageMachines/LamaEvents#2]
### Summary
[lamaevents.cls.ru.nl](http://lamaevents.cls.ru.nl/) returns 503 error right now because it is not running on the servers.

### Steps to run it on current Applejack server
- Start a new screen on Applejack server. [Click to see _screen_ commands](http://aperiodic.net/screen/quick_reference) 
- Activate the virtual environment that contains 
- Run `runserver.sh` script in the environment in the created screen section. 
- `runserver.sh` runs the Django server, so it should run continuously. So, detach (leave) the screen without terminating the project

**Comment by ghiathghanem** [comment]
I did the followings:
- Connected to Applejack server.
- Create a new environment (Gh_env)
- Run runserver.sh
Now the website is online.

**Comment by ErkanBasar** [comment]
Great! Now the website is online. I'm closing the issue.
